// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE51_xCeJFFpjis_ZUohWFvvT4CK2fNp8',
    appId: '1:697477829289:web:dcf67081b2567221d68fb8',
    messagingSenderId: '697477829289',
    projectId: 'gentleman-s-forge',
    authDomain: 'gentleman-s-forge.firebaseapp.com',
    storageBucket: 'gentleman-s-forge.appspot.com',
    measurementId: 'G-4021MTE375',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfwOh6FuJwW5b705uBVzEMcpDvnebR1AQ',
    appId: '1:697477829289:android:c02474cb9349c486d68fb8',
    messagingSenderId: '697477829289',
    projectId: 'gentleman-s-forge',
    storageBucket: 'gentleman-s-forge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC65-ZEPnNHHNLsIAsKd2_2o2Mdh9WyeF4',
    appId: '1:697477829289:ios:ab8ad2499ebf6768d68fb8',
    messagingSenderId: '697477829289',
    projectId: 'gentleman-s-forge',
    storageBucket: 'gentleman-s-forge.appspot.com',
    iosClientId: '697477829289-hdkh0n2h3dkdgv0b8fjjpbmhc1q91ilq.apps.googleusercontent.com',
    iosBundleId: 'com.dally.technologies.gentelmanForge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC65-ZEPnNHHNLsIAsKd2_2o2Mdh9WyeF4',
    appId: '1:697477829289:ios:4461f87dc8feea27d68fb8',
    messagingSenderId: '697477829289',
    projectId: 'gentleman-s-forge',
    storageBucket: 'gentleman-s-forge.appspot.com',
    iosClientId: '697477829289-6jevi4oes3fkp8ijtnmuu4htg8sv57uj.apps.googleusercontent.com',
    iosBundleId: 'com.dally.technologies.gentelmanForge.RunnerTests',
  );
}
